# Numpy basics

In [1]:
import numpy as np

### List example

In [93]:
my_list = [1,2,3,4,5]
type(my_list)

list

### Converting list to array

In [94]:
arr = np.array(my_list)
type(arr)

numpy.ndarray

### Array representation

In [95]:
arr

array([1, 2, 3, 4, 5])

### Shape of array
##### (row, column)

In [96]:
arr.shape

(5,)

### Reshaping array

In [97]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

### 2-D array

In [98]:
my_list1 = [1,2,3,4,5]
my_list2 = [5,6,7,8,9]
my_list3 = [9,3,6,7,4]
arr2 = np.array([my_list1,my_list2,my_list3])

In [99]:
arr2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 3, 6, 7, 4]])

In [100]:
arr2.shape

(3, 5)

### 2-D array reshaping

In [101]:
arr3 = arr2.reshape(5,3)
arr3

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 9, 3],
       [6, 7, 4]])

In [102]:
arr3.shape

(5, 3)

### Array indexing

In [103]:
arr

array([1, 2, 3, 4, 5])

In [104]:
arr[3]

4

### Array slicing

In [105]:
arr2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [9, 3, 6, 7, 4]])

In [106]:
arr2[0:2,1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [107]:
arr2[1:2,1:4]

array([[6, 7, 8]])

### Arange method
##### (start, stop, step)

In [108]:
arr4 = np.arange(0,10,3)
arr4

array([0, 3, 6, 9])

### Linspace method
##### (start, stop, numbers)

In [109]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

### Use .copy() to avoid aray overriding

In [110]:
arr5 = arr.copy()
arr5[3:] = 999
arr5

array([  1,   2,   3, 999, 999])

In [111]:
arr

array([1, 2, 3, 4, 5])

### Condition checking

In [112]:
arr < 3

array([ True,  True, False, False, False])

### Array of Ones
Return a new array of given shape and type, filled with ones

In [113]:
np.ones(4)

array([1., 1., 1., 1.])

In [114]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [115]:
np.ones((2,4), dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Array of Zeros
Return a new array of given shape and type, filled with zeros

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros_like

### Random method

##### .rand(rows, columns)
Random values in a given shape

In [2]:
np.random.rand(4,3)

array([[0.62394814, 0.40210907, 0.17504887],
       [0.40487483, 0.34051666, 0.5553348 ],
       [0.03665002, 0.77361449, 0.94814162],
       [0.56630737, 0.27212059, 0.05956367]])

##### .randn(rows, columns)
Return a sample (or samples) from the "standard normal" distribution

In [117]:
arr_ex = np.random.randn(4,4)
arr_ex

array([[-1.93996395, -1.34077908,  0.53990001,  1.40692841],
       [ 1.65920006,  0.88462106,  2.28868094,  1.29972852],
       [ 2.86075672, -0.90440703,  1.11827955,  0.01122129],
       [-1.30144295, -0.55527843, -1.3038849 , -1.15755175]])

##### .randint(low, high, size)
Return random integers from `low` (inclusive) to `high` (exclusive)

In [118]:
np.random.randint(0,100,8)

array([60, 92, 11, 20, 57, 46, 45, 85])

In [119]:
np.random.randint(0,100,8).reshape(2,4)

array([[24, 97, 47, 69],
       [33, 93, 95, 67]])

##### .random_sample()
Return random floats in the half-open interval [0.0, 1.0)

In [120]:
np.random.random_sample((1,5))

array([[0.87614788, 0.47999111, 0.30423898, 0.10879568, 0.49162947]])